spring:
  application:
    name: mysql-consumer
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: my-12398aa98
    hikari:
      idle-timeout: 10000
      maximum-pool-size: 100
    jdbc-url: jdbc:mysql://localhost:3306/test


kafka:
  default:
    url: localhost:9091
    producer:
      acks: all
    consumer:
      group.id: ${spring.application.name}

replication:
  include-schemas: test