spring:
  application:
    name: mysql-consumer

kafka:
  default:
    url: localhost:9091
    producer:
      acks: all
  topic:
    schemas-snapshot:
      name: schemas-snapshot
      consumer:
        group.id: ${spring.application.name}.${kafka.topic.schemas-snapshot.name}
    tables-snapshot:
      name: tables-snapshot
      consumer:
        group.id: ${spring.application.name}.${kafka.topic.tables-snapshot.name}
    insert:
      name: insert
      consumer:
        group.id: ${spring.application.name}.${kafka.topic.insert.name}
    update:
      name: update
      consumer:
        group.id: ${spring.application.name}.${kafka.topic.update.name}
    delete:
      name: delete
      consumer:
        group.id: ${spring.application.name}.${kafka.topic.delete.name}