replication:
  plugin-name: pg_mysql_decoder
  slot-name: test
  include-schemas:
    - test
  lsn-table-name: public.last_lsn


logical-replication:
  slot-name: test

kafka:
  default:
    url: localhost:9092
    producer:
      acks: all
  topic:
    create-schema:
      name: create_schems
    create-table:
      name: create_table
#    dml-operation:
#      name: dml_operation


spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://localhost:5434/postgres
    username: a.merenova
    password: 1
    hikari:
      idle-timeout: 10000